### ISSUE TITLE
Cannot show the chart 

### ISSUE THREAD

**Issue by NancyZY** [tomauty/react-native-chart#101]
Sorry for no reply at a moment,here is dependencies from my package.json file:

  "dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.23.1",
    "react-native-chart": "^0.1.14",
    "react-native-menu": "^0.20.1",
    "react-native-swipeout": "^2.0.12",
    "react-timer-mixin": "^0.13.3"
  }

and the screen still shows the red rectangle.

**Comment by tomauty** [comment]
Oh, so you'll want to install the latest, which is now `1.0.4-beta` :)

**Comment by tomauty** [comment]
Sorry, now it's 1.0.5-beta hehe
