### ISSUE TITLE
XAxis is not correctly placed. It's marginLeft might not work.

### ISSUE THREAD

**Issue by jakkra** [tomauty/react-native-chart#102]
Running on Android, latest React-Native version.
Also, to get anything to show except x/y axis, I had to add  `showDataPoint={true}`
It's not only the x-axis that's not correctly aligned, the grid seems to be a few pixels to high.

Using your sample [code](https://gist.github.com/jakkra/06d1ac70c1c88b7231c9ba094202526b):

![chart](https://cloud.githubusercontent.com/assets/4318648/16713829/78cd3692-46b3-11e6-8717-90cf6071320c.png)

**Comment by tomauty** [comment]
Dang, I fixed this same thing on iOS a while back :p

**Comment by doddys** [comment]
It seems like the xAxis.js is not using style props passed down by Chart.js

I added the following code in xAxis.js  and it seems that it works

```
<View
  style={[
    styles.xAxisContainer,
    {
         borderTopColor: this.props.axisColor,
         borderTopWidth: this.props.axisLineWidth,
    },
    this.props.style,
  ]}
>
```

is this a the right way to fix this?

**Comment by doddys** [comment]
just "this.props.style," part

**Comment by tomauty** [comment]
Good call, that's probably it. Expect in `1.0.8` as soon as I can

**Comment by KalebPortillo** [comment]
+1
Experiencing the same issue

**Comment by KalebPortillo** [comment]
@tomauty Any estimative for the 1.0.8 release?
Cheers

**Comment by tomauty** [comment]
1.0.8-beta is out. Feedback appreciated :)

**Comment by KalebPortillo** [comment]
I tested out and it seems to be all fixed up
Thanks
