### ISSUE TITLE
Data array pair with string?

### ISSUE THREAD

**Issue by KalebPortillo** [tomauty/react-native-chart#106]
Is it possible to make a data array pair with number and string? 
For example:

```
let data = [
   ["Monday", 75],
   ["Tuesday", 75],
   ["Wednesday", 75]
]
```

**Comment by tomauty** [comment]
I don't see why not. As far as I know we don't actually read any numerical value from the first entry in a pair, just display it in the xAxis. However there's no truncation in place, so it might be good to utilize the new `xAxisTransform` to fit them all :)

**Comment by tomauty** [comment]
Can you re-open if that solution doesn't work for you?
