### ISSUE TITLE
Failed propType: Required prop `chartData`

### ISSUE THREAD

**Issue by ErrorPro** [tomauty/react-native-chart#109]
Hello. I took an example from README.md and tried to set it up. I got these two errors:
`Warning: Failed propType: Required prop`chartData`was not specified in`RNChart`. Check the render method of`Stats``
`Warning: Failed propType: Required prop `xLabels` was not specified in `RNChart`. Check the render method of `Stats`.`

And everything i see is a red square.

I set up the last version of react-native also. I tried to reinstall RNChart lib, relinked it. Can anybody help me with it?

**Comment by tomauty** [comment]
Are you running the latest beta build? `1.0.7-beta`?

**Comment by ErrorPro** [comment]
No, i am running ^0.1.4 version.

**Comment by tomauty** [comment]
Can you try the beta version? The README is outdated for that version. Alternatively, if you have to use the Obj-C branch, I can point you to an old README file.
