### ISSUE TITLE
BarChart has not the correct alignment

### ISSUE THREAD

**Issue by a-marcel** [tomauty/react-native-chart#12]
Hello,

i use you react native module and it's realy nice, but i see, that a bar plot is not corrected aligned on the x-axis. You can see it in the scrrenshot: 
![bildschirmfoto 2015-08-06 um 22 33 48](https://cloud.githubusercontent.com/assets/4396769/9122778/7c0a14c0-3c8b-11e5-9cd4-f63db61a31c1.png)

How can i fix that ?

Thanks
Marcel

**Comment by tomauty** [comment]
Can you post some sample code for this? Make sure to try with the newest version (0.1.3 at time of writing). Since it's been so long, I'll close this for the sake of keeping sane, but please let me know if this is still an issue.

**Comment by tomauty** [comment]
I've made some adjustments to alignment recently. Can someone verify this is still an issue? Seems to work for me now.

**Comment by nico75005** [comment]
I'm not sure we're talking about the same issue here as for me there are two on this chart.

The first one being the gap between the x-axis and the bars (a space seems to be randomly present between the x-axis and some bars), it has been fixed.
The second one being that the bars are not centered on the x-axis like the numbers on the x-axis are:

![screen shot 2016-05-10 at 11 58 05](https://cloud.githubusercontent.com/assets/1647328/15131707/7eaedd32-16a6-11e6-81e2-ecc403c77896.png)

And it becomes more obvious when you reduce the widthPercent parameter (to 0.1 in this case). You can also see that the numbers on the x-axis aren't centered any more either.

![screen shot 2016-05-10 at 11 59 35](https://cloud.githubusercontent.com/assets/1647328/15131752/d62e84d6-16a6-11e6-8969-748de13a0a7a.png)
