### ISSUE TITLE
Couldn't locate libRNChart.a

### ISSUE THREAD

**Issue by ittikorns** [tomauty/react-native-chart#13]
I've followed the first three steps and stuck at the fourth step. Can't find "libRNChart.a" in the list of "Link Binary with Libraries" or in the source folder.

In XCode, in the project navigator, select your project. Add libRNChart.a to your project's Build Phases ➜ Link Binary With Libraries

**Comment by johnnyoshika** [comment]
If you completed step 3, `` should be in the list of libraries that you can link.  Here's what my select dialog looks like.  What does yours look like?

![image](https://cloud.githubusercontent.com/assets/504505/9985331/f96eaa36-5fde-11e5-85e2-e4b831b556e4.png)

**Comment by tomauty** [comment]
I imagine this is resolved. I will be updating the README shortly to also detail how to use it with `rnpm`. Re-open if not.
