### ISSUE TITLE
Line Style of Grid

### ISSUE THREAD

**Issue by msom** [tomauty/react-native-chart#136]
It would be nice to be able to change the line style of the grid (solid, dashed, dotted) in the future. Unfortunately this is not possible at the moment due to a bug in react native: https://github.com/facebook/react-native/issues/3159 :(.

**Comment by tomauty** [comment]
As a generic FYI — I am no longer able to maintain this library. I recommend checking out [victory-native](https://github.com/FormidableLabs/victory-native) as it's much more maintained.
