### ISSUE TITLE
Multi Chart Implementation Breaks Grid and Axis

### ISSUE THREAD

**Issue by msom** [tomauty/react-native-chart#137]
The multichart implementation https://github.com/tomauty/react-native-chart/commit/597394b99b37d6d8038d988deee0498b16916b3d breaks various things such as the x-axis and horizontal grid.

**Comment by tomauty** [comment]
As a generic FYI — I am no longer able to maintain this library. I recommend checking out [victory-native](https://github.com/FormidableLabs/victory-native) as it's much more maintained.
