### ISSUE TITLE
How to use the xAxisTransform property.

### ISSUE THREAD

**Issue by lin493369** [tomauty/react-native-chart#154]
Since I want to use the xAxisTransform function,but the document does't show how it work.
Cloud someone tell me how to  use the xAxisTransform property.

**Comment by msom** [comment]
xAxisTransform expects a function which takes the x-Value and returns the transformed value (int, string, null, ...), see [here](https://github.com/tomauty/react-native-chart/blob/92b51953176faf383f45238e0bdf7d86c9a4022f/src/xAxis.js#L62).

For example to invert the labels, use:
```
let xLabels = (i) => -i
<Chart xAxisTransform={xLabels}>
```

**Comment by lin493369** [comment]
@msom Thanks a lot!Sorry for late to reply you.
