### ISSUE TITLE
horizontalGridStep

### ISSUE THREAD

**Issue by maicaiyao** [tomauty/react-native-chart#16]
Hello thanks for this awesome component! I have a quick question about the coming features. 
1. Will there be support for setting horizontalGripStep soon?  
2. Will I be able to put the name of the data beside the end of the line?

Do you have plan implementing the above features? Thanks for the help!

**Comment by tomauty** [comment]
Can you give more information on what each of those points implements?

**Comment by tomauty** [comment]
Horizontal grid step will be added shortly

**Comment by tomauty** [comment]
Axis title does now work for both X and Y. If that's not what you're looking for, let me know and I'll re-open.
