### ISSUE TITLE
FIXED REPO

### ISSUE THREAD

**Issue by robcalcroft** [tomauty/react-native-chart#161]
**https://github.com/robcalcroft/react-native-chart**

As the state of this repo seems to be unknown, I forked the repo and fixed a breaking bug for RN@0.39.0. Haven't tested on @0.40.0 but will report back when I do. I will also actively merge any PRs into my fork if you'd like one place to fix stuff that this repo hasn't 😄 

**EDIT**
I have moved to using https://github.com/FormidableLabs/victory-native I suggest you use that over this framework. They're doing great work and are actively maintaining victory-native 😄

**Comment by zphhhhh** [comment]
Thank you! But how do I use your fixed Repo?  `npm i react-native-chart --save` will install tomauty's, but not yours.

**Comment by robcalcroft** [comment]
@zphhhhh `npm install git+https://git@github.com/robcalcroft/react-native-chart.git`

**Comment by zphhhhh** [comment]
Thanks again! And it works on @0.40.0 well~

**Comment by excellencetechnologies** [comment]
Line chart creating issue ,like missing some part of showDataPoint in the graph .

**Comment by tomauty** [comment]
As a generic FYI — I am no longer able to maintain this library. I recommend checking out [victory-native](https://github.com/FormidableLabs/victory-native) as it's much more maintained.

**Comment by robcalcroft** [comment]
@tomauty thanks for letting us know
