### ISSUE TITLE
The package react-native@0.6.0 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by nosensezzz** [tomauty/react-native-chart#18]
Hi, I think you specify using the version react native 0.4.0, which is not able to use under my 0.6.0, can you make it like > 0.4.0 so we can use your component?

**Comment by nosensezzz** [comment]
I manually changed the package.json file and release myself to npm, and then install it, it works now

**Comment by johnnyoshika** [comment]
Oops, it looks like I created a duplicate issue: https://github.com/onefold/react-native-chart/issues/20

Can you elaborate on how you fixed this?  Where did you release an updated package.json?

Thanks!

**Comment by nosensezzz** [comment]
Hi, Johnny

in the package.json, there is a "peerDependencies", you need to specify it to ">0.4.0", then you are good to go.

I modify the package.json file and release the module again myself, you are welcome to use it, you can do npm install react-native-chart-nosensezzz to install it, it same as this one but it support latest react-native framework.

Anyway, I do not suggest you use this chart because the writer is gone!!! But I have no alternative to use, sigh, I hope react-native team could build one.

**Comment by johnnyoshika** [comment]
Ah, got it.  Thank you.  I ended up forking this repo, making the same changes as you, and installing it directly from GitHub.  I submitted a pull request, but it hasn't been merged yet:

https://github.com/onefold/react-native-chart/pull/21
