### ISSUE TITLE
Use peerDependencies

### ISSUE THREAD

**Issue by lwansbrough** [tomauty/react-native-chart#2]
https://github.com/onefold/react-native-chart/blob/master/package.json#L9

It's more advantageous to use `peerDependencies` as opposed to `dependencies` for the `react-native` depedency - it saves us from re-downloading react-native for each module when we already have it installed.

**Comment by lwansbrough** [comment]
Addressed in this PR: https://github.com/onefold/react-native-chart/pull/3

**Comment by hyuncho** [comment]
Sounds good.
