### ISSUE TITLE
labelFontSize doesn't work

### ISSUE THREAD

**Issue by johnnyoshika** [tomauty/react-native-chart#23]
`labelFontSize` isn't working.
### Example 1: labelFontSize 7

```
        <RNChart style={styles.chart}
          chartData={chartData}
          verticalGridStep={5}
          xLabels={xLabels}
          labelFontSize={7}>
        </RNChart>
```

![image](https://cloud.githubusercontent.com/assets/504505/10047472/31caac00-61c3-11e5-8864-1d194f4271c3.png)
### Example 2: labelFontSize 12

```
        <RNChart style={styles.chart}
          chartData={chartData}
          verticalGridStep={5}
          xLabels={xLabels}
          labelFontSize={12}>
        </RNChart>
```

![image](https://cloud.githubusercontent.com/assets/504505/10047533/853f157e-61c3-11e5-95be-c400b5884f51.png)

Regardless of the `labelFontSize` setting, the font size remains the same.

**Comment by nickmaxwell10** [comment]
@johnnyoshika, did you ever find a workaround for this?

**Comment by johnnyoshika** [comment]
@nickmaxwell10, unfortunately, no.

**Comment by tomauty** [comment]
Will be looking into this.

**Comment by tomauty** [comment]
@johnnyoshika can you send me the chart data and styles so I can easily test this?

**Comment by johnnyoshika** [comment]
@tomauty: this was from 4 months ago, so I'm not sure if I still have it, but I'll see if I can dig it up.  :-)

Thanks for following up though.

**Comment by tomauty** [comment]
Hah, yeah, thought it'd be worth a shot ;)

**Comment by L-Jovi** [comment]
the same issue, any idea now?

**Comment by tomauty** [comment]
Should have a fix this week

**Comment by tomauty** [comment]
v0.1.7 :+1:
