### ISSUE TITLE
linking error while integrating react-native-chart

### ISSUE THREAD

**Issue by bandishankar** [tomauty/react-native-chart#25]
I am getting following error while adding onefold react native chart in my application . It is a linking error but i have already added all library . 

Ld /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/AwesomeProject1.app/AwesomeProject1 normal x86_64
    cd /Users/shanba6/AwesomeProject1/ios
    export IPHONEOS_DEPLOYMENT_TARGET=7.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator -F/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator -filelist /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Intermediates/AwesomeProject1.build/Debug-iphonesimulator/AwesomeProject1.build/Objects-normal/x86_64/AwesomeProject1.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=7.1 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -fobjc-arc -fobjc-link-runtime /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRNChart.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libReact.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTImage.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTLinking.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTNetwork.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTSettings.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTText.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTVibration.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a -Xlinker -dependency_info -Xlinker /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Intermediates/AwesomeProject1.build/Debug-iphonesimulator/AwesomeProject1.build/Objects-normal/x86_64/AwesomeProject1_dependency_info.dat -o /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/AwesomeProject1.app/AwesomeProject1

ld: warning: object file (/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRNChart.a(RNChartAxisView.o)) was built for newer iOS version (9.0) than being linked (7.1)
ld: warning: object file (/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRNChart.a(RNChartView.o)) was built for newer iOS version (9.0) than being linked (7.1)
ld: warning: object file (/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRNChart.a(RNChartPlotAreaView.o)) was built for newer iOS version (9.0) than being linked (7.1)
ld: warning: object file (/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRNChart.a(RNChartViewManager.o)) was built for newer iOS version (9.0) than being linked (7.1)
Undefined symbols for architecture x86_64:
  "_RCTCopyProperty", referenced from:
      -[RNChartViewManager set_chartData:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_verticalGridStep:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_animationDuration:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_showGrid:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_gridColor:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_gridLineWidth:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_showAxis:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      ...
  "_RCTSetProperty", referenced from:
      -[RNChartViewManager set_chartData:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_verticalGridStep:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_animationDuration:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_showGrid:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_gridColor:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_gridLineWidth:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_showAxis:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
###### 

Ld /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/AwesomeProject1.app/AwesomeProject1 normal x86_64
    cd /Users/shanba6/AwesomeProject1/ios
    export IPHONEOS_DEPLOYMENT_TARGET=7.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator -F/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator -filelist /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Intermediates/AwesomeProject1.build/Debug-iphonesimulator/AwesomeProject1.build/Objects-normal/x86_64/AwesomeProject1.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=7.1 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -fobjc-arc -fobjc-link-runtime /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRNChart.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libReact.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTImage.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTLinking.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTNetwork.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTSettings.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTText.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTVibration.a /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a -Xlinker -dependency_info -Xlinker /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Intermediates/AwesomeProject1.build/Debug-iphonesimulator/AwesomeProject1.build/Objects-normal/x86_64/AwesomeProject1_dependency_info.dat -o /Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/AwesomeProject1.app/AwesomeProject1

ld: warning: object file (/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRNChart.a(RNChartAxisView.o)) was built for newer iOS version (9.0) than being linked (7.1)
ld: warning: object file (/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRNChart.a(RNChartView.o)) was built for newer iOS version (9.0) than being linked (7.1)
ld: warning: object file (/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRNChart.a(RNChartPlotAreaView.o)) was built for newer iOS version (9.0) than being linked (7.1)
ld: warning: object file (/Users/shanba6/Library/Developer/Xcode/DerivedData/AwesomeProject1-ezoxvgkiizqjhsftoxrkntfykjsp/Build/Products/Debug-iphonesimulator/libRNChart.a(RNChartViewManager.o)) was built for newer iOS version (9.0) than being linked (7.1)
Undefined symbols for architecture x86_64:
  "_RCTCopyProperty", referenced from:
      -[RNChartViewManager set_chartData:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_verticalGridStep:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_animationDuration:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_showGrid:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_gridColor:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_gridLineWidth:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_showAxis:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      ...
  "_RCTSetProperty", referenced from:
      -[RNChartViewManager set_chartData:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_verticalGridStep:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_animationDuration:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_showGrid:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_gridColor:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_gridLineWidth:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      -[RNChartViewManager set_showAxis:forView:withDefaultView:] in libRNChart.a(RNChartViewManager.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tehong** [comment]
I encountered the same problem when manually added the unzipped react-native-chart to my xCode project after following the README directions.   Any luck getting through this problem?

**Comment by bandishankar** [comment]
I am still waiting to get it resolved , I hope they will give some support over it .

**Comment by tehong** [comment]
Bandi,

Thanks for replying, hopefully someone can take a look at this.  In the
mean time, a question for you. Did you find another RN module to do
charting in RN environment?  So far I've not found other RN charting
modules that can do line charts directly.

Eric

**Comment by bandishankar** [comment]
I did't find anything other than this , but I am thinking to start looking into library code and will try to take out my concerned module out of it .

**Comment by tehong** [comment]
I'm not sure what you mean "library code".  Are you talking about RN native
module?  I am thinking putting iOS CorePlot line chart Obj-C and my old
swift code under a RN native module and use it that way.

Eric

**Comment by bandishankar** [comment]
Ya I mean RN native module . But I am not sure about it . I can't use swift
code in my project .

**Comment by tehong** [comment]
Bandi,

If you can use Obj-C then it should be alright.  However, it's unclear to
me how one can easily put something like CorePlot iOS, which implements
Obj-C  UIView, under RN native module.  I may have to experiment with that.

Eric

**Comment by tomauty** [comment]
Please try again with the newest version (0.1.3 at time of writing). If the manual method doesn't work, try:

```
npm install -g rnpm
rnpm link
```

Will be updating the readme soon to include this.
