### ISSUE TITLE
error with react-native version 0.13.0-rc

### ISSUE THREAD

**Issue by bt404** [tomauty/react-native-chart#26]
Hi, I install the module by `npm install https://github.com/onefold/react-native-chart --save`，and the version of react-native I installed is 0.13.0-rc. The console now shows as below and I have a runtime error in RNChartView.m line 55. The message is `Error setting property 'verticalGridStep' of RNChartView with tag #8: JSON value '5' of type NSString cannot be converted to NSNumber`.

```
Unable to resolve module ReactPropTypes from /Users/MLS/mls/biz/dc_native/SexyDc/node_modules/react-native-chart/Chart.ios.js
Unable to resolve module ReactNativeViewAttributes from /Users/MLS/mls/biz/dc_native/SexyDc/node_modules/react-native-chart/Chart.ios.js
Unable to resolve module createReactNativeComponentClass from /Users/MLS/mls/biz/dc_native/SexyDc/node_modules/react-native-chart/Chart.ios.js
Unable to resolve module StyleSheet from /Users/MLS/mls/biz/dc_native/SexyDc/node_modules/react-native-chart/Chart.ios.js
Unable to resolve module NativeMethodsMixin from /Users/MLS/mls/biz/dc_native/SexyDc/node_modules/react-native-chart/Chart.ios.js
Unable to resolve module flattenStyle from /Users/MLS/mls/biz/dc_native/SexyDc/node_modules/react-native-chart/Chart.ios.js
Unable to resolve module merge from /Users/MLS/mls/biz/dc_native/SexyDc/node_modules/react-native-chart/Chart.ios.js
```

How can I solve the problem? Thanks.

**Comment by bt404** [comment]
OK, I have solved the problem. The reason is the value of param 'color' is wrong. I can't set the variable of type string, eg: 'gray', 'blue' etc. I should set it an array of float standing for rgb value([0.8, 0.5, 0.1]).

**Comment by aroth** [comment]
https://github.com/facebook/react-native/issues/3300

**Comment by tomauty** [comment]
This is a todo item of mine, to support strings for proptypes like this. Will keep you updated.

**Comment by tomauty** [comment]
#40
