### ISSUE TITLE
Unable to do npm install of the react-native-chart

### ISSUE THREAD

**Issue by tehong** [tomauty/react-native-chart#27]
I was unable to do npm install due to the following error with my react-native 0.12.0.  I appears that the dependency of the react-native-chart prevent npm from going forward.  It looks like this repository is still stuck in the old react-native 0.4.0

$ npm install react-native-chart --save
npm WARN peerDependencies The peer dependency react-native@^0.4.0 included from react-native-chart will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/Eric/.nvm/versions/node/v4.1.2/bin/node" "/Users/Eric/.nvm/versions/node/v4.1.2/bin/npm" "install" "react-native-chart" "--save"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native@0.12.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-chart@0.0.4 wants react-native@^0.4.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Eric/GitHub/Mi-KPI/npm-debug.log

**Comment by nickmaxwell10** [comment]
+1

**Comment by wootwoot1234** [comment]
+1

**Comment by linqingwu75** [comment]
+1

**Comment by linqingwu75** [comment]
hope it can support latest version of react-native.

**Comment by tomauty** [comment]
This will be fixed when I can bump the npm version.

**Comment by tomauty** [comment]
Should be fixed in v0.1.1

**Comment by wootwoot1234** [comment]
@tomauty  Thanks!

**Comment by tomauty** [comment]
Actually make sure to get 0.1.3 just so ya know. ^0.1.3 should suffice :+1:
