### ISSUE TITLE
Redraw/refresh chart with new values appended in array

### ISSUE THREAD

**Issue by dmota-systango** [tomauty/react-native-chart#28]
Hi.. While using this API, I wanted to redraw the graph with updated values of the array.. But once it is plotted it gives me the error saying "Attempt to write read only values.'

**Comment by gurisko** [comment]
+1

**Comment by wootwoot1234** [comment]
+1

**Comment by tomauty** [comment]
I agree this is essential to the survival of this library. Making it a priority.

**Comment by tomauty** [comment]
Hm, can you overwrite the data array reference entirely? That seems to work for me, as far as re-drawing is concerned.

**Comment by tomauty** [comment]
I'll look into the use case for changing an array by value, but am tempted to keep the behavior as it is, since it's in line with how most libraries handle reference checking nowadays.

**Comment by tomauty** [comment]
Closing this since replacing the object such that it's a new reference will take care of this.
