### ISSUE TITLE
Axis values get too dense for more values

### ISSUE THREAD

**Issue by dmota-systango** [tomauty/react-native-chart#31]
Hi..While plotting graphs, for a larger set of values on X-axis the values get too dense and overlap each other.
![densevalues_axis](https://cloud.githubusercontent.com/assets/2918973/10966481/d9ab3326-83d9-11e5-8317-a6a4654b3ec8.png)

**Comment by tomauty** [comment]
What would be the ideal behavior here?

**Comment by Taakn** [comment]
Ideally being able to manually specify an angle for the labels so that they don't overlap anymore.

**Comment by tomauty** [comment]
Okay, I've changed the title of #19 to specify this. Closing this one.
