### ISSUE TITLE
why can't get archive on target ios 7/8?

### ISSUE THREAD

**Issue by bt404** [tomauty/react-native-chart#32]
When running on ios 7/8, the app will crash.

**Comment by bt404** [comment]
OK. Because the `RNChartPlotAreaView/getLinePath` method get a `scale` variable valued `+INF`, so the app will crash in code `[path moveToPoint:p]`. Adding the coding below:

```
if (scale == +INFINITY) {
    scale = 0;
}
```

fixed the problem.

**Comment by tomauty** [comment]
Can you elaborate on where you made this change?

**Comment by bt404** [comment]
At the top of  `getLinePath` method in `RNChartPlotAreaView.m` file.

**Comment by tomauty** [comment]
Can't seem to get that to happen, but I do get it to crash when I force it to `+INFINITY`. It's a good guard to have if it's a problem. Will add in.

**Comment by tomauty** [comment]
0.1.6
