### ISSUE TITLE
Invalid directory /Users/node_modules/ReactPropTypes

### ISSUE THREAD

**Issue by L-Jovi** [tomauty/react-native-chart#36]
I get this issue with below description

```
Unable to resolve module ReactPropTypes from /Users/jovi/AwesomeProject/node_modules/react-native-chart/Chart.ios.js: Invalid directory /Users/node_modules/ReactPropTypes
```

but I indeed follow step from [getting-started](https://github.com/onefold/react-native-chart#getting-started) 

could anybody help me ?
thanks..

**Comment by tomauty** [comment]
When we bump the version (after I do some tests), this should be resolved. This is what happens when RN is looking for a node module that it can't find.

**Comment by L-Jovi** [comment]
great, thanks
