### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by tomauty** [tomauty/react-native-chart#37]
Are you looking for a maintainer for this project? I'm willing to put in some work if you are. This is a project that the community is dying to use.

**Comment by hyuncho** [comment]
I just added you as a collaborator.  As a collaborator can you pull requests from other contributors?

**Comment by tomauty** [comment]
Yes, that's the case. Thank you! I'll do it justice :)

**Comment by tomauty** [comment]
I'd also want to be an npm collaborator, if you're willing to let me publish.

**Comment by tomauty** [comment]
cc @hyuncho :)

**Comment by hyuncho** [comment]
@tomauty I'll let you know today.

**Comment by hyuncho** [comment]
@tomauty I just added you as a collaborator on npm.

**Comment by tomauty** [comment]
Thank you! Hope to do this project well :)
