### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by Taakn** [tomauty/react-native-chart#39]
I don't believe there is but do you plan on having Android support?

Thanks so much

**Comment by tomauty** [comment]
I'd love to, but it'd be a bit down the road. I do plan on supporting Android with this eventually, so keep an eye on it :)

**Comment by tomauty** [comment]
In particular, I'd be curious to see how difficult it'd be to migrate this project to use React Native ART, since that's been open-sourced.

**Comment by Taakn** [comment]
@tomauty Just wondering if you have an idea of a timeline to get this compatible with Android. Do you know what's working / not working with Android? Thanks so much for your work!

**Comment by tomauty** [comment]
To be honest, android support would require either a separate Java implementation or a full rewrite. At the moment, I'm implementing minor features in hope of exploring more reusable patterns for the library. If you're up for the challenge, I certainly welcome pull requests! Otherwise, maybe March. Depends on my work schedule in a way.

**Comment by tomauty** [comment]
That is to say, nothing is working in android because all implementation is in objective c. Transition to ART is the expected route, but no crystal clear path in sight yet. I would even welcome comments on which pieces could be implemented using ART.

**Comment by Taakn** [comment]
ok thanks for your comments. I'm at a point in my project where I need to find a charting library compatible with iOS and Android. I'm going to start looking into what's available and ART, and I'll let you know if I find anything interesting for your project. Thanks again!
