### ISSUE TITLE
use `dataPointFillColor` in chartData error

### ISSUE THREAD

**Issue by L-Jovi** [tomauty/react-native-chart#41]
I don't know how to change `dataPointFillColor` at js side, when I directly specify string value `#98E489` below error occured, 
maybe I'll call `processColor()` somewhere?,

could you help me? thanks..

```
JSON value '#98E489' of type NSString cannot be converted to a UIColor. Did you forget to call processColor() on the JS side?
```

**Comment by tomauty** [comment]
Added to props processing in 0.1.6, try that and let me know :)

**Comment by L-Jovi** [comment]
it works! thank you : )
