### ISSUE TITLE
make horizontal chart?

### ISSUE THREAD

**Issue by L-Jovi** [tomauty/react-native-chart#43]
very smart project, may I have two suggestion here?
1. how could I make horizontal chart when I choose `type: 'bar'`
2. any options that making chart interactively? maybe highlight is enough.

thanks for your time..

**Comment by tomauty** [comment]
Interactivity is in the pipeline. First step will be to set a data point to highlight with a highlight color and index. As far as horizontal, it's not possible now but I'll make it happen. Will split into two issues.

**Comment by tomauty** [comment]
#45 and #44, respectively.
