### ISSUE TITLE
Support 'horizontalGridStep'

### ISSUE THREAD

**Issue by tomauty** [tomauty/react-native-chart#46]

**Comment by esutton** [comment]
The chart below has three X:Y points ranging from 0 to 114
- Is there anyway to make the first grid line appear at 0
- Display grid lines at 0, 50, 100, and 150

Or will this require a new **horizontalGridStep** feature?

 <img width="668" alt="horizontalgridstep" src="https://cloud.githubusercontent.com/assets/6115047/13996114/535529ce-f0fa-11e5-8784-00a59b6f0240.png">

Thank you for react-native-chart !

**Comment by tomauty** [comment]
The first point is something I want to fix independently. The second is `horizontalGridStep`. Hoping early next week for both.

**Comment by esutton** [comment]
That's great news @tomauty

I am amazed your Objective C source code accomplishes so much and is still clean, concise, and readable. Thank you for sharing your work!

**Comment by tomauty** [comment]
`horizontalGridStep` requires too much thought from the library user, IMO. I'm learning towards the solution being thought through here: https://github.com/tomauty/react-native-chart/issues/62
