### ISSUE TITLE
Remove support for multiple charts

### ISSUE THREAD

**Issue by tomauty** [tomauty/react-native-chart#49]
This would fundamentally change the API, but I don't understand the need for an array of chart data vs one chart per component. Could someone enlighten me on the use case for this? It's becoming more complicated to support new chart types when it's possible to have more than one per component (e.g. Pie chart)

**Comment by mahlon-gumbs** [comment]
Hi there. We actually have a need for a multi-line chart. Is this your question is about? We've got two series of financial data we need to display as separate lines in the same chart. It would look like something similar to http://jsfiddle.net/mQMH3/3/

**Comment by tomauty** [comment]
That works for me. I think I'll just throw an error if someone tries to use more than one type of chart at once. That's been the difficult piece to reconcile.

**Comment by tomauty** [comment]
BTW that should be possible with the current API.

**Comment by mahlon-gumbs** [comment]
Are you saying “Multi-line charts” work with the current API? And it’s only multiple charts (for example, a line chart overlay on a bar chart) that causes problems?  I didn’t think multi-line charts worked. I'll have to check again (but even your Known Issues/TODO suggests they are not supported at this time).

**Comment by tomauty** [comment]
You're right, my mistake. I'll have to check what happens when multiple lines are provided :)
