### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by KyleAMathews** [tomauty/react-native-chart#5]
Would make it easier to evaluate this module.

**Comment by a-marcel** [comment]
You can see some here:

![bildschirmfoto 2015-08-06 um 22 33 48](https://cloud.githubusercontent.com/assets/4396769/9122727/3ba607f4-3c8b-11e5-941d-1e9237f02a2d.png)

**Comment by lloydh6** [comment]
+1

**Comment by tomauty** [comment]
If anyone has any to add, feel free to post them here. I'll create some nice ones eventually.

**Comment by rgoldiez** [comment]
+1 ... interested to see some screenshots before diving in to this one.

**Comment by tomauty** [comment]
I will be updating the README with an RNPlay example and some screenshots of that this week

**Comment by wliment** [comment]
@tomauty  could you make a example code for the pie charts?

**Comment by tomauty** [comment]
Ya, I will be doing that. Unfortunately the pie chart isn't _super_ robust, but I had to release it for an internal project.

**Comment by tomauty** [comment]
Added some to README, will be publishing the Example project momentarily :)
