### ISSUE TITLE
Text overflow ellipsis when using big numbers (yAxis)

### ISSUE THREAD

**Issue by Mokto** [tomauty/react-native-chart#51]
How can I prevent that ?

![img_0065](https://cloud.githubusercontent.com/assets/5103928/13264249/3fc53582-da3b-11e5-8114-e94849e5c199.PNG)

Thanks !

**Comment by tomauty** [comment]
Might have to add an `offset` property for this. Will get back to you. Possible to post a code snippet to make this happen? :)

**Comment by Mokto** [comment]
I can but I took your example and have set values 999. It seems that 1000 => 1 000 => textoverflow but I'm not sure.

Do you really need it ? :)

**Comment by tomauty** [comment]
Nah, just if you have a quick one to send over I could look, but I'll experiment with `offset` anyway. Will be useful for general chart styling.

**Comment by Mokto** [comment]
Hi man ! Any update on this ? ;)

Thanks.

**Comment by tomauty** [comment]
I'll try to get it updated today or tomorrow :)

**Comment by Mokto** [comment]
Thanks :)

**Comment by tomauty** [comment]
Hi, apologies for the delay. I've been working on the pure JS version of this library. I think all I need to do is allow a custom yAxisWidth property. Will try my best to add it in this week. Also would accept a PR.

**Comment by tomauty** [comment]
Fixed in `1.0.0-beta`.
