### ISSUE TITLE
Pie chart off-centre 

### ISSUE THREAD

**Issue by brycepavey** [tomauty/react-native-chart#53]
Pie chart centring is slightly off to the right. This can be seen in the screenshot from the readme.md, as well as my own application (shown in screenshot)

![screen shot 2016-02-29 at 10 55 00 am](https://cloud.githubusercontent.com/assets/6986339/13382880/f0e1dcd0-ded2-11e5-8ecb-8c474bb1c8fd.png)

**Comment by tomauty** [comment]
This will be fixed next release.

**Comment by tomauty** [comment]
Fixed in 0.1.13
