### ISSUE TITLE
Is there a way to format yAxis labels?

### ISSUE THREAD

**Issue by mahlon-gumbs** [tomauty/react-native-chart#54]
Looking through the source I didn't find a way, but I wanted to make sure I'm not missing something.

**Comment by tomauty** [comment]
Format in what sense? D3 style transform from the data?

**Comment by mahlon-gumbs** [comment]
Yes. Though I’d take something as simple as passing in an array of pre-formatted labels simile to how xLabels are handled.  Possible?

**Comment by tomauty** [comment]
It certainly could be. I think it could just check for presence of that array when choosing y-labels, over choosing from the data array. Might take a bit of work but I think it's a good thing to have.

**Comment by tomauty** [comment]
Will be adding a `yAxisTransform` property in 2.0 :)

**Comment by Mindaugas-Jacionis** [comment]
yAxisTransform - will transform only labels, or maybe it will also allow you to switch y axis from left to right?

**Comment by tomauty** [comment]
`yAxisTransform` is in `1.0.0-beta`
