### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by aspafford** [tomauty/react-native-chart#55]
Hi, I'm having some trouble getting the readme example to work. I'm only seeing a red border around where the chart should be displayed. I'm using react native 0.21.0 and iOS 9.2.

**Comment by tomauty** [comment]
Make sure you run 'rnpm link' :)

**Comment by aspafford** [comment]
Thanks for the quick reply. I did try running 'rnpm link' but unfortunately still have the same issue.

**Comment by tomauty** [comment]
Hey, I'll be home tomorrow and can try it out. You might have to manually
link the library via the react native instructions linked in the read me.
I'll make sure linking is seamless next release. The red border is a
symptom of the library being unlinked, so that is assuredly the issue :)

**Comment by aspafford** [comment]
Yes, manual linking fixed it. thanks!
