### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by QuinnStephens** [tomauty/react-native-chart#56]
Are there plans to add Android support?

**Comment by tomauty** [comment]
I've gotten this question a few times, and truth be told it's a pretty big task. However, the team I'm working on also needs an Android-compatible version soon. My plan is to move from CoreAnimation to React Native ART for the drawing functions, but obviously this will be a big endeavor. Know that it is on the way, and should hopefully (fingers crossed) be ready in the next few weeks.

**Comment by QuinnStephens** [comment]
Good to know, thank you!

**Comment by tomauty** [comment]
Going to close this but will start on a PR this week.
