### ISSUE TITLE
Lines doesn't start at minBounds when using tightBounds and fillColor

### ISSUE THREAD

**Issue by cesardeazevedo** [tomauty/react-native-chart#57]
Awesome lib, 

I'm using `tightBounds` with a vertical range about 1500-1520 and i realize that lines doesn't start at the bottom (1500), It starts in a long way down, instead of the `minBounds` of the `tightBounds`.

I've slow down the animationDuration to show it, you can also see the `fillColor` ended much higher than expected.
![issue](https://cloud.githubusercontent.com/assets/5366959/13721134/361bd34c-e7fb-11e5-86d7-fddf5de6dbde.gif)

It's only occurs when sets `fillColor` property.

I've played a little bit on the [path scale](https://github.com/tomauty/react-native-chart/blob/master/RNChartPlotAreaView.m#L89-L93), but no success yet, any progress i'd pull request, any help would be appreciated.

**Comment by tomauty** [comment]
Have you tried setting a static height on the chart component?

**Comment by cesardeazevedo** [comment]
It doesn't really help, i think there's something wrong with the [fillAnimation.fromValue](https://github.com/tomauty/react-native-chart/blob/master/RNChartPlotAreaView.m#L143) and [pathAnimation.fromValue](https://github.com/tomauty/react-native-chart/blob/master/RNChartPlotAreaView.m#L164) animation.

**Comment by tomauty** [comment]
I agree, those have been a point of frustration for me. Would you mind
posting a snippet so I can debug?

**Comment by cesardeazevedo** [comment]
Sure, following the [index.ios.js](https://github.com/tomauty/react-native-chart/blob/master/Example/RNChartExample/index.ios.js) example. I made these changes to you reproduce it, https://gist.github.com/cesardeazevedo/109f60e77f97c76ce484

**Comment by tomauty** [comment]
Would you be willing to try out `1.0.1-beta` ? It's a ground-up rewrite so this problem probably doesn't exist anymore :)
