### ISSUE TITLE
Bar chart not displaying single data point properly

### ISSUE THREAD

**Issue by shanemcgraw** [tomauty/react-native-chart#60]
From all I can see in the docs, there isn't a way to customize the display of specific bars in the chart- only the styles of the chart as a whole. 

This becomes problematic when trying to display a bar chart containing only a single data point (e.g. chart data being something like `[30]`) - it's showing the data from the very left, instead of getting centered on the chart. I set `xLabels` to ['0'].

From a bar chart taken from the example in the readme and slightly modified to contain a single data point, I'm getting something like this:

<img width="377" alt="screen shot 2016-03-18 at 12 22 34 pm" src="https://cloud.githubusercontent.com/assets/10692718/13889526/3eb5d1fc-ed04-11e5-8309-032de2b05332.png">

Is there any way to center the data?

**Comment by tomauty** [comment]
Got your email too, sorry for the delay. The alignment of data points in general will hopefully be fixed next release.

**Comment by tomauty** [comment]
Fixed in 0.1.13

**Comment by shanemcgraw** [comment]
Many thanks, @tomauty!
