### ISSUE TITLE
Interactive Chart

### ISSUE THREAD

**Issue by tomauty** [tomauty/react-native-chart#67]
Here's my first draft of what an interactive chart might be comprised of:

The **press** event

``` javascript
{
  coordinates: {
    x: number,    // X-coordinate on the device
    y: number,    // Y-coordinate on the device
  },
  didPressDataPoint: boolean,   // to help you decide whether or not to show a view or some such thing
  closestDataPoint: DataPoint   // this will make more sense as 2.0 gets fleshed out, but an instance of a DataPoint object
}
```

The **events**
`onPressIn`
`onPressOut`

The `Chart` will emit these events, and as such you will be able to attach listeners to them via the `ref`.

Please feel free to comment about feedback, questions, etc. I want this to be as community-involved as possible.

**Comment by prithsharma** [comment]
@tomauty Since the 2.0 milestone has been marked complete, is this supported yet?

EDIT - I found the `onDataPointPress` property. I think this must be the one. Thanks.

**Comment by prithsharma** [comment]
Is this done yet?
It seems `onDataPointPress` is implemented only for `BarChart`.
