### ISSUE TITLE
Hiding y-axis

### ISSUE THREAD

**Issue by nico75005** [tomauty/react-native-chart#70]
Is there a way to hide the y-axis bar?

I didn't find anything regarding the matter.
I mean yes, there is a way to do it by adding `axisLineWidth={0}` but then I can't have the x-axis line and I need it.

And by the way, when I set `showGrid={true}` is it normal to have the x-axis removed?

**Comment by Mindaugas-Jacionis** [comment]
As a hack I absolute positioned my chart and added left negative value. So it is there but user can not see it. :)

**Comment by tomauty** [comment]
This should be available in 1.0.0-beta
