### ISSUE TITLE
React native 0.26

### ISSUE THREAD

**Issue by bkniffler** [tomauty/react-native-chart#73]
Latest react native doesn't include react any more. It is now necessary to pull `React, { Component, PropTypes }` from `react`-package, and not from `react-native`.

Any chance to see this coming as a default for the next versions of your chart library?

**Comment by tomauty** [comment]
yep, working off the latest RC right now

**Comment by cablegunmaster** [comment]
How to get this one? via npm? version 2.0 on git? 
With the npm version I got a error, which indicates my import is not working:

Error I got:
`Super expression must either be null or a function, not undefined`
On line:
`import RNChart from 'react-native-chart';
`

This happens after following all the steps on the readme.md for the android version, and trying to work with it.

Npm says: react-native-chart@0.1.14

**Comment by esutton** [comment]
@tomauty what is git URL for your latest RC?  Is RC a public branch?

Or just https://github.com/tomauty/react-native-chart.git  ?

react-native-chart is my last package to get working with 0.26.2

Thanks!

**Comment by alimek** [comment]
I have the same issue when installed:

Error I got:
`Super expression must either be null or a function, not undefined`
On line:
`import RNChart from 'react-native-chart';`

RN 0.26.2

**Comment by asantos00** [comment]
I'm having the same issue as @alimek

**Comment by HectorFL** [comment]
Me too.

**Comment by dhfmzk** [comment]
Me too.

**Comment by tomauty** [comment]
I think I'm going to release 2.0 today. Latest RN fixed arc drawing issues for pie charts. :)

**Comment by YuxinChou** [comment]
Waiting for 2.0 release

**Comment by mathjoy** [comment]
is 2.0 ready?

**Comment by Choujiji** [comment]
waiting 2.0

**Comment by tomauty** [comment]
Finalizing the README and API use tomorrow. Expect some bugs to be sure, but it seems mostly stable. Fingers crossed.

**Comment by boblad** [comment]
waiting for 2.0

**Comment by ggaabe** [comment]
How do you recommend going about installing the 2.0 branch?

**Comment by boblad** [comment]
@tomauty any updates on this?

**Comment by jln-dk** [comment]
Any updates on 2.0 release date?

**Comment by HectorFL** [comment]
Using the 2.0 I get:  "Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `SimpleChart`"

Any idea? Thanks.

**Comment by txizzle** [comment]
@HectorFL how did you install 2.0?

**Comment by HectorFL** [comment]
Easy, download the branch 2.0 from here, put the folder react-native-charts-2.0 in node_modules inside your project folder and run: $ rnpm link react-native-charts-2.0 in the terminal for the dependencies.

**Comment by txizzle** [comment]
Any commands you ran after that?
I downloaded the 2.0 branch, put the folder in node_modules, and then ran `rnpm link react-native-chart-2.0`, and then attempted to build the RN app. 

However, I get this error: `TransformError:/myprojectfolder/node_modules/react-native-chart-2.0/index.ios.js:__DEV__ is not defined`. The project also takes a lot longer to find dependencies, is this normal?

**Comment by ggaabe** [comment]
I'm not quite sure how to get around this issue, but this 2.0 branch requires a lower version of react than I have, and it's throwing me an error. I run:

`npm install https://github.com/tomauty/react-native-chart#2.0`

which throws

`UNMET PEER DEPENDENCY react@15.1.0
npm WARN react-native@0.26.3 requires a peer of react@15.0.2 but none was installed.`

My react-native version is 0.27.2 and my installed react version is 15.1.0. Shouldn't it not be throwing any errors if my React version is higher?

**Comment by tomauty** [comment]
I'm going to make this release-ready as is today, with a beta tag. I'm
sorry for holding this all up, hopefully we can make it really good
together!

**Comment by tomauty** [comment]
`1.0.0-beta` is out now. Please please give feedback and help! Appreciated!!

**Comment by KishPatel1996** [comment]
Getting a element type is invalid: expected a string(for build-in components) or a class/function....

any idea of what is causing this?  I just copied/pasted the example code in
