### ISSUE TITLE
Smooth line chart

### ISSUE THREAD

**Issue by Mindaugas-Jacionis** [tomauty/react-native-chart#74]
Maybe I am missing something here, but I can not seem to get line chart not so edgy. More smooth like this: https://www.extendoffice.com/images/stories/doc-excel/smooth-line-chart/doc-smooth-line-chart-2.png

As I can see in the documentation there is no property to smooth it out, or it should be done differently? Maybe something like this is coming in v2.0? :)

**Comment by tomauty** [comment]
I'm not sure how ReactART supports path interpolators, if at all, but I will look into it.

**Comment by tomauty** [comment]
Going to merge this with #100 since it's closer to a bezier solution.
