### ISSUE TITLE
Support for key-value pairs?

### ISSUE THREAD

**Issue by SpaceRangerWes** [tomauty/react-native-chart#75]
I was curious if you had support for key-value pair data in mind for the future? For example if I have

``` javascript
{
   Black: 50,
   Blue: 10,
   Yellow: 5,
   Teal: 45,
}
```

and then I wanted a linear graph with color v. amount where I could say `data = dictionary_variable`?

**Comment by tomauty** [comment]
Open to the PR. I'm currently transitioning to data sets with the following shape:

```
[ [x1, y1], [x2, y2], ... ]
```

**Comment by cablegunmaster** [comment]
Also wondering, what about multi line  like a example in this shape:
`
[ [x1, y1, y1], [x2, y1, y1], ... ]
`

Idea is every Y has its own color. Highest number first. so it could process a negative chart and a positive chart in 1 chart.

**Comment by tomauty** [comment]
I'm inclined to support @cablegunmaster 's proposal over key/value pairs. For the use-case described by OP, I can always add in `xAxisTransform` to accomplish this mapping.

**Comment by tomauty** [comment]
An interesting third option would be something like...

``` javacript
{
   Black: [50, 0],
   Blue: [10, 20],
   Yellow: [5, 10],
   Teal: [45, 5],
}
```

I could see potentially supporting data of the form `Object<key, Array<number...>` but it seems to be sugar to avoid calling a (now-nonexistent, I admit!) `xAxisTransform` function. Thoughts welcome.

**Comment by tomauty** [comment]
I'm going to close this out without justification for explicitly supporting dictionaries as data sets. I've implemented `xAxisTransform` in the latest release, and in reality the first entry of any data pair can be anything as long as it's supported as a child of `<Text />`. Feel free to re-open if there is a good justification for dictionary data values.
