### ISSUE TITLE
Did it support Android

### ISSUE THREAD

**Issue by hkc452** [tomauty/react-native-chart#77]
Just as  I say above,did it support android or just ios onlu

**Comment by vladpodobed** [comment]
+

**Comment by cablegunmaster** [comment]
"did" is past tence , does it ... Tom is working hard on making it work with android :+1: 
Either specify your question better as did it support version X. or X. or just the newest? 
See: https://github.com/tomauty/react-native-chart/issues/59

**Comment by tomauty** [comment]
iOS right now. #59 is where i'll post progress. We're pretty close...
