### ISSUE TITLE
sliceColors prop having no effect on pie chart

### ISSUE THREAD

**Issue by ggaabe** [tomauty/react-native-chart#81]
Hi again :D 

So I was trying to pass an array of strings of colors to the sliceColors attribute of the pie chart. Unfortunately, it has been a no go (insofar as being able to change the default colors).

Is this the proper way of doing it?

`<Chart style={styles.chart} data={pieData} showAxis={false} type="pie" sliceColors={['rgb(41,116,231)', 'rgb(0,163,46)']}/>`

**Comment by tomauty** [comment]
yes, it should be. will look into it now.

**Comment by tomauty** [comment]
Hah, found it :p Will be fixed next update (end of day today)

**Comment by ggaabe** [comment]
woot. I'll be making one more issue and then we should be all dandy.

**Comment by ggaabe** [comment]
Hey, I'm still not getting sliceColors to show different colors.
Is this the right way to do it? Or am I messing something up?
`sliceColors={['rgb(41,116,231)', 'rgb(0,163,46)']}`

**Comment by tomauty** [comment]
Sorry, maybe shouldn't have closed yet. I'll do another npm release shortly
to resolve it.

Tom

**Comment by tomauty** [comment]
`1.0.1-beta` is up

**Comment by ggaabe** [comment]
Thanks! It works!

Dude, you're legendary.

**Comment by tomauty** [comment]
😃
