### ISSUE TITLE
[1.0.1-beta] Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by txizzle** [tomauty/react-native-chart#83]
Same issue as pre-beta, not sure why. 

Steps I followed: 
1. `npm i react-native-chart --save`
2. Linked ART following the instructions
3. Started React Native Server
4. Build in xcode
5. Get the error.

Did I miss any steps?

Thanks!

**Comment by tomauty** [comment]
Hi, the minimum RN version is now 0.25 for the beta release. That's a
symptom of having an older version.

Tom

**Comment by txizzle** [comment]
Yep, I'm on react-native@0.27.2

**Comment by GodOnlyKnow** [comment]
+1

**Comment by tomauty** [comment]
Oh, which actual version of the library are you using? Anything pre `1.0.0-beta` is no longer maintained really.

**Comment by tuananhdn** [comment]
:( did 1.0.1-beta support multi line in 1 chart.

**Comment by aliouchka** [comment]
hi, i have the same issue, any solution ? thx

**Comment by cablegunmaster** [comment]
@tuananhdn , @aliouchka  please post more info :

Project-> package.json
          react:  X ?
          react-native: X?
          react-native-chart: X?

**Comment by aliouchka** [comment]
"react": "^15.1.0",
"react-native": "^0.27.2",
"react-native-chart": "^0.1.14",

didn't see the rnc version...how can i update please ?

**Comment by cablegunmaster** [comment]
@aliouchka Try deleting the 'node_modules' folder and installing again. 
This usually resolves some dependency issues.

Inside the project package.json folder.

```
$npm i react-native-chart --save
$rnpm link
```

Hopefully this would help.
Gonna check myself got the same versions aliouchka.

**Comment by tomauty** [comment]
@aliouchka if the above doesn't work, try `npm install --save react-native-chart@^1.0.1-beta`

**Comment by aliouchka** [comment]
It worked (with the first one), thank you, it's cool :)

**Comment by txizzle** [comment]
Sorry that I'm still having trouble with this! I don't know why this is so difficult for me, seems like it went smoothly for most other people.

So I just tried to make a new project from scratch, and got a new error ('
What I did:
1. `react-native init TestPackage`
2. `npm install --save react-native-chart@^1.0.1-beta` 
3. Link ART as in instructions
4. `npm install babel-plugin-transform-flow-strip-types` (otherwise the packager tells me I need it)
5. `react-native run-ios`
6.  ReferenceError: **DEV** is not defined

Not sure if I missed something! Full error message is:
`> ReferenceError: **DEV** is not defined

> ```
> at Object.<anonymous> (***/node_modules/react-native/Libraries/react-native/react-native.js:15:5)
> at Module._compile (module.js:435:26)
> at Object.Module._extensions..js (module.js:442:10)
> at Module.load (module.js:356:32)
> at Function.Module._load (module.js:311:12)
> at Module.require (module.js:366:17)
> at require (module.js:385:17)
> at ***/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:391:22
> at Array.map (native)
> ```
> 
> TransformError: ***/node_modules/react-native-chart/dist/Chart.js: **DEV** is not defined
> [6:17:33 PM] <START> request:/index.ios.bundle?platform=ios&dev=true`

Thanks again! Can't wait to get it working.
