### ISSUE TITLE
Debugging in chrome

### ISSUE THREAD

**Issue by boblad** [tomauty/react-native-chart#84]
With react-native-chart beta 1.0 when I try to debug in chrome  via the ios simulator I get a blank white screen (Android works just fine). I removed ART.xcodeproj from the libraries, removed all uses of RNChart but left `import RNChart from 'react-native-chart'`. My project would run fine but just without my charts, As soon I linked ART.xcodeproj back into the libraries with the chrome debugger on I would get the blank white screen again. After I turned off debug in chrome and imported ART and linked it all up again. All of my charts ran just fine. So for me debugging in chrome with ART.xcodeproj is breaking stuff. Im using react native 0.26.3, Any Ideas?

**Comment by tomauty** [comment]
Wow, that's a new one. No output in the chrome console?

**Comment by boblad** [comment]
@tomauty I dont get any errors at all

**Comment by petroslafaz** [comment]
I think this is a general Remote debugging problem which is fixed on 0.27+. Otherwise there is a solution which requires to replace RCTBatchedBridge.m with an older version 
https://github.com/facebook/react-native/issues/7635

**Comment by tomauty** [comment]
Ah right, I do remember having to do that in test builds. My bad. I'm not sure if I can be much help here. Feel free to re-open if it turns out to be package specific.

**Comment by boblad** [comment]
@petroslafaz Fixed. Thanks!
