### ISSUE TITLE
Implement xAxisTransform

### ISSUE THREAD

**Issue by nickmaxwell10** [tomauty/react-native-chart#86]
My x-axis data are timestamps (seconds since the epoch) and I would like to display the dates on the x-axis.  Any way to do this right now?

**Comment by tomauty** [comment]
Hey Nick,

You should be able to pass anything into the first entry of a data pair, if
I'm not mistaken. I know the signature says <number, number>, but it should
just put whatever raw text you give it into the x-axis. Otherwise I'll be
working on an xAxisTransform function this week.

Tom

**Comment by nickmaxwell10** [comment]
Tom, 

Thanks for your reply.  An xAxisTransform function would be a great addition..  I ended up implementing something similar in my project last night. 

Nick

**Comment by tomauty** [comment]
`1.0.6-beta` implements this. If it breaks anything let me know.
