### ISSUE TITLE
Android line chart?

### ISSUE THREAD

**Issue by Mindaugas-Jacionis** [tomauty/react-native-chart#88]
Hi,

does newest beta support Android for line charts?

**Comment by tomauty** [comment]
It does!

**Comment by Mindaugas-Jacionis** [comment]
```
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import Chart from 'react-native-chart';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white',
    },
    chart: {
        width: 200,
        height: 200,
    },
});

const data = [
    [0, 1],
    [1, 3],
    [3, 7],
    [4, 9],
];

class testGraph extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Chart
                    style={styles.chart}
                    data={data}
                    verticalGridStep={5}
                    type="line"
                 />
            </View>
        );
    }
}

export default testGraph;
```

Am I missing something? This is iOS and Android screenshots: 

![screen shot 2016-06-21 at 16 47 12](https://cloud.githubusercontent.com/assets/8435507/16233837/f49c6830-37cf-11e6-9f50-e4e77e32c800.png)

**Comment by tomauty** [comment]
That's weird, I'll investigate. Apologies.

**Comment by Mindaugas-Jacionis** [comment]
No worries, should have posted code and screenshots initially. Thanks a lot for your support!

**Comment by peterbozso** [comment]
I looked into it and the problem seems to be coming from the the fading animation of the View, here: https://github.com/tomauty/react-native-chart/blob/master/src/LineChart.js#L103
If I remove it, like this: https://gist.github.com/uruk/9c78bff4b68972f6fa74d78111a01497 , then it works fine.

**Comment by tomauty** [comment]
Oh that's bizarre. I'll put that in on a platform basis. Thanks for your help @uruk

**Comment by tomauty** [comment]
Can you try `1.0.4-beta`? I removed dependencies on `LayoutAnimation`, and also added `animated` as an optional boolean proptype. If this still persists with your current case, please re-open.

**Comment by tomauty** [comment]
Nevermind. I fixed it by disabling animations in master for Android. Will restore as a `TODO` item.
