### ISSUE TITLE
[1.0.1-beta] ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by txizzle** [tomauty/react-native-chart#89]
Sorry that I'm still having trouble with this! I don't know why this is so difficult for me, seems like it went smoothly for most other people.

So I just tried to make a new project from scratch, and got a new error 
What I did:
1. `react-native init TestPackage`
2. `npm install --save react-native-chart@^1.0.1-beta` 
3. Link ART as in instructions
4. `npm install babel-plugin-transform-flow-strip-types` (otherwise the packager tells me I need it)
5. `react-native run-ios`
6.  ReferenceError: **DEV** is not defined

Not sure if I missed something! Full error message is:
`> ReferenceError: **DEV** is not defined

> ```
> at Object.<anonymous> (***/node_modules/react-native/Libraries/react-native/react-native.js:15:5)
> at Module._compile (module.js:435:26)
> at Object.Module._extensions..js (module.js:442:10)
> at Module.load (module.js:356:32)
> at Function.Module._load (module.js:311:12)
> at Module.require (module.js:366:17)
> at require (module.js:385:17)
> at ***/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:391:22
> at Array.map (native)
> ```
> 
> TransformError: ***/node_modules/react-native-chart/dist/Chart.js: **DEV** is not defined
> [6:17:33 PM] <START> request:/index.ios.bundle?platform=ios&dev=true`

Thanks again! Can't wait to get it working.

**Comment by tomauty** [comment]
Actually the package doesn't really check for `__DEV__`, so this looks like an error with your RN installation.

**Comment by txizzle** [comment]
Gotcha, thanks. Will explore that.
