### ISSUE TITLE
Requiring unknown module "ReactIOSViewAttributes"

### ISSUE THREAD

**Issue by mgechev** [tomauty/react-native-chart#9]
I got:

> Requiring unknown module "ReactIOSViewAttributes". If you are sure the module is there, try restarting the packager.

However, [here I saw](https://github.com/bsudekum/react-native-mapbox-gl/issues/35) the module is removed in React Native 0.4.3 and the current release candidate is `0.5.0`.

**Comment by joshhornby** [comment]
Same for me, the bug renders the package unusable :(

**Comment by aroth** [comment]
@mgechev @joshhornby This has been fixed, but the release is not on NPM. Install from the GitHub source:

npm install https://github.com/onefold/react-native-chart --save

**Comment by mgechev** [comment]
Ok, great! I think we can close this one :-)

**Comment by thekennysong** [comment]
@aroth thanks for your comment! Really appreciate it. :)
