### ISSUE TITLE
Cannot show the chart 

### ISSUE THREAD

**Issue by NancyZY** [tomauty/react-native-chart#92]
When I was build the RN project , write code like sample, I just saw the red square.I don't know what's wrong. Hope you can save my time .Thanks. This is iOS screenshots: 
￼
![simulator screen shot jun 24 2016 2 38 35 pm](https://cloud.githubusercontent.com/assets/9473445/16330086/672aae2a-3a19-11e6-9fe0-23bd6ab0f541.png)

and the code is like that:

``` javascript
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import Chart from 'react-native-chart';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white',
    },
    chart: {
        width: 200,
        height: 200,
    },
});

const data = [
    [0, 1],
    [1, 3],
    [3, 7],
    [4, 9],
];

class testGraph extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Chart
                    style={styles.chart}
                    data={data}
                    verticalGridStep={5}
                    type="line"
                 />
            </View>
        );
    }
}

export default testGraph;
```

￼

**Comment by tomauty** [comment]
hmm I've seen this before on other modules. Has to do with linking, installation problems, some such thing. I'll get back to you shortly

**Comment by NancyZY** [comment]
@tomauty Thanks for the reply. But I have to say I followed the steps that you've noticed, and double-check the steps, no results for this reason. That's spent much time.

**Comment by tomauty** [comment]
You did link ReactART in Xcode, correct?

**Comment by NancyZY** [comment]
yes, there is a  problem?

**Comment by tomauty** [comment]
Hmm not sure. Which version of the library are you on? Can you post the package.json item?

**Comment by tomauty** [comment]
Please reopen with any new information.
