### ISSUE TITLE
line chart is not like ways doing

### ISSUE THREAD

**Issue by Angela-yuxiang** [tomauty/react-native-chart#93]
Hey,tomauty:
     When I set the data to element , the show  works, but it not work well. I mean set the data array was that : const data = [ [0, 1],[1, 3], [3, 7], [6, 11],];  but the chart shows that:
![simulator screen shot jun 26 2016 5 28 20 pm](https://cloud.githubusercontent.com/assets/13639555/16361425/42823308-3bc3-11e6-949f-36e14308f67a.png)
the Y axis not right,and the X Axis data is right but the space not work good.

**Comment by naivehhr** [comment]
+1

**Comment by cablegunmaster** [comment]
Dataset doesn't start with Y = 0 , but with the default value of the first array. 
Should be a boolean added yAxisStartOnZero or First value.

**Comment by tomauty** [comment]
Agreed to the above. Also getting the Y-Axis position correct on line charts is a priority.

**Comment by tomauty** [comment]
Can you try `1.0.4-beta` and let me know if this persists? I might've taken care of this.
