### ISSUE TITLE
labelFontSize doens't work 

### ISSUE THREAD

**Issue by KalebPortillo** [tomauty/react-native-chart#95]
Hello, I'm trying to modify the numbers size in my chart, i tried to pass de font size to the following props but not happens: labelFontSize, chartFontSize;
I need to have smaller number sizes.

Thanks

**Comment by tomauty** [comment]
Can you try the latest master branch? Just added support for `labelFontSize` here: https://github.com/tomauty/react-native-chart/commit/0da0eb38b2ed504f6f97e9a4567701fd3ac9ce13

**Comment by tomauty** [comment]
Will be out next beta release today

**Comment by KalebPortillo** [comment]
Thanks @tomauty, its working
