### ISSUE TITLE
In some cases charts don't fit the container

### ISSUE THREAD

**Issue by spukhov** [tomauty/react-native-chart#96]
![2016-07-01 00 31 44](https://cloud.githubusercontent.com/assets/4569555/16504963/56646edc-3f23-11e6-9052-a88bbd9a3e9a.png)

You can see it with the higher data points.

Also https://github.com/tomauty/react-native-chart/issues/90 is reproduced here. 
For the first chart data is ["Jul", 33], but it shows about 20.
For the last chart data is ["Jun", 88], but it looks more like 44 in chart.

**Comment by tomauty** [comment]
Can you post the code that makes those charts if possible?

**Comment by KalebPortillo** [comment]
+1
its happening with me too, with the same code of the Readme

**Comment by tomauty** [comment]
Ah okay. I will check it out. The README code should work, at the very least... :p

**Comment by KalebPortillo** [comment]
What seems to happen is that for a given data : [x, y], the higher value in y always stay outside of bonds, and the second higher y value stay on the top

**Comment by KalebPortillo** [comment]
This issue was fixed for me when I updated for the version 1.0.6-beta
@spukhov have you tried update?

**Comment by tomauty** [comment]
I fixed plenty of line chart things since originally posted, and it seems to be resolved. If not, please re-open.
