### ISSUE TITLE
Line chart seems to bug out if the first datapoint is the highest

### ISSUE THREAD

**Issue by carbureted** [tomauty/react-native-chart#97]
As the title says. Any idea where one should start looking to hunt this down? My config seemed fairly innocuous.

`data = [
      [0, 0],
      [1, 1],
      [2, 0],
      [3, 0],
      [3, 2]
  ]`

![workinggraph](https://cloud.githubusercontent.com/assets/597441/16508108/7dc97c18-3ee4-11e6-8aa4-651dbfa1dd83.png)

`data = [
      [0, 3],
      [1, 1],
      [2, 0],
      [3, 0],
      [3, 2]
  ]`

![brokengraph](https://cloud.githubusercontent.com/assets/597441/16508113/87e1eb86-3ee4-11e6-9ca8-802e3cfd01ba.png)

```
        <Chart
          style={chartStyles.chart}
          data={data}
          gridColor={"rgba(255,255,255,0.2)"}
          axisColor={"rgba(255,255,255,0.2)"}
          color="#ED7467"
          verticalGridStep={0}
          type="line"
          dataPointColor="#ED7467"
          dataPointFillColor="#ED7467"
          fillColor="#76494E"
          showDataPoint={true}
          dataPointRadius={1}
          lineWidth={1}
          showXAxisLabels={false}
          tightBounds={true}
          />
```

Thanks for the awesome library!

**Comment by tomauty** [comment]
Fixed by https://github.com/tomauty/react-native-chart/commit/c04a634c02b4c5984ff050eef5342f0e72edab77

Release coming momentarily.
